construction_rental.settings:
  type: config_object
  label: 'Construction Rental settings'
  mapping:
    advance_percentage:
      type: integer
      label: 'Advance percentage'
    preferred_payment_gateway:
      type: label
      label: 'Preferred payment gateway id'
